version: '3.9'

services:
  app:
    build: .
    container_name: furia-app
    restart: always
    volumes:
      - ./data:/app/data
    expose:
      - "8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - TZ=America/Sao_Paulo

  nginx:
    image: nginx:latest
    container_name: furia-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
